gantt
    title Feature Enhancement Roadmap
    dateFormat  YYYY-MM-DD
    section Release 2.0
    Parse message log to eliminate noise using AI   :a1, 2022-07-01, 15d
    Host reboots    :after a1  , 15d

    section Release 3.0
    UPS power alerts     :2022-08-01  , 5d
    RPA high load alerts     : 5d
    RPA high load alerts    : 5d
    Detect an unauthoried user     : 5d