graph LR
    B(Jonny Le<br/>Digital Wizard, Team Leader,<br/> and Developer)
    B --- C(Tom Tar<br/>Chief of Escalation and Comic Relief<br/>Marp Specialist)
    C --- D(Gabrielle Woods<br/> Conceptualization Engineer<br/>Marp Specialist)
    D --- E(Bob Matos<br/> Master of Disaster<br/>Developer)
    E --- F(Rak Kalra<br/>Swiss Army Knife<br/>Developver)
    F --- G(Summer Markley<br/>Professional Cat Herder<br/>PM and Presenter)